### ISSUE TITLE
CORS error for the first few requests on the fresh deployment of the plugin

### ISSUE THREAD

**Issue by rjnrohit** [NethermindEth/starknet-remix-plugin#105]
<img width="1423" alt="Screenshot 2023-09-11 at 12 36 55 PM" src="https://github.com/NethermindEth/starknet-remix-plugin/assets/47271616/b193699e-cf35-473b-a276-9f1cda30a68a">

**Comment by stranger80** [comment]
Wait till ECS-hosted plugin is on, then check if this still persists.

**Comment by Sahitya777** [comment]
is this resolved still facing some problems with the cors issue?

**Comment by rjnrohit** [comment]
this has been fixed! Issue doesn't appear anynmore
