### ISSUE TITLE
[Bug] Some Cairo contract read functions not appearing in Interact panel

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#107]
Steps to reproduce:

Plugin version 0.1.0, use Remote Devnet

1. Create a new cairo file with following content:
```
#[starknet::contract]
mod HelloCairo {
    #[storage]
    struct Storage {}

    #[view]
    fn hello_cairo() -> felt252 {
      return 'Hello Cairo!';
    }
}
```
2. Compile
3. Deploy
4. The "Interact" does not display the `hello_cairo()` contract method for interaction.

**Comment by stranger80** [comment]
After review - the contract submitted seems to be using "outdated" lancguage constructs/attrbiutes. 

The cairo compiler sould probably flag those as "deprecated"??? or give some other warning...

**Comment by rjnrohit** [comment]
How do we know that the person is using the outdated cairo lang for writing the contract ?
