### ISSUE TITLE
Rename the remix plugin record in Remix directory

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#116]
The Starknet plugin is getting some use, and the https://remix.ethereum.org/?#activate=Starknet-cairo1-compiler link is beginning to be used by some tutorials. This link label should be renamed to more generic "Starknet". 

- [x] Ethereum Remix directory change request PR: https://github.com/ethereum/remix-plugins-directory/pull/355
- [x] Starknet by Example link update PR: https://github.com/NethermindEth/StarknetByExample/pull/78
- [x] WTF Academy links need to be updated. 0xAA from WTF Academy has been notified about the change.

**Comment by julio4** [comment]
Remix directory and Starknet by Example was updated successfully.
