### ISSUE TITLE
Starknet cairo compile not working

### ISSUE THREAD

**Issue by 0xtradeall** [NethermindEth/starknet-remix-plugin#127]
Starknet cairo compile is not working. I have failed to fetch message. please help

**Comment by EdgarBarrantes** [comment]
Thanks a lot for the report! Could you give us more details? (screenshot of browser console, Remix console, network tab...)

**Comment by Kuper8** [comment]
Вот такая ошибка когда жмешь Compile
![11111](https://github.com/NethermindEth/starknet-remix-plugin/assets/131158645/c76325ec-02d9-4ae4-a743-662bb686a154)

**Comment by EdgarBarrantes** [comment]
@Kuper8, спасибо, мы проверим это как можно скорее

**Comment by stranger80** [comment]
@0xtradeall, @Kuper8, can we ask you for a few more details of this behaviour? We suspect CORS-related problem, but to be clear, would you like to fill in the details as per below?

**To Reproduce**
Steps to reproduce the behavior (from a clean start):
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Cairo files**
Please include the Cairo source file.

**Starknet Remix Plugin details**
- Are you using the default Starknet plugin from Remix marketplace, or any self-configured plugin instance?
- What Environment are you using (Remote/Local Devnet, a wallet configuration)?

**Host system (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari], any nonstandard browser plugins/adblocks
 - Version [e.g. 22]

**Comment by khanmuddu** [comment]
> @0xtradeall, @Kuper8, can we ask you for a few more details of this behaviour? We suspect CORS-related problem, but to be clear, would you like to fill in the details as per below?
> 
> **To Reproduce** Steps to reproduce the behavior (from a clean start):
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **NOTE:** Please clearly indicate the time (with timezone or in UTC) when you have observed the error.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Cairo files** Please include the Cairo source file.
> 
> **Starknet Remix Plugin details**
> 
> * Are you using the default Starknet plugin from Remix marketplace, or any self-configured plugin instance?
> * What Environment are you using (Remote/Local Devnet, a wallet configuration)?
> 
> **Host system (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari], any nonstandard browser plugins/adblocks
> * Version [e.g. 22]

**Comment by Kuper8** [comment]
![111](https://github.com/NethermindEth/starknet-remix-plugin/assets/131158645/eb3486da-0882-4cdc-ae94-cd3e1f0656e3)
Hello ! I tried again,  but a new error appeared. No buttom to compile, attached a screenshots a below. See error
![222](https://github.com/NethermindEth/starknet-remix-plugin/assets/131158645/7ef9b378-d813-4f43-b4fd-33db5b52b245)
![3333](https://github.com/NethermindEth/starknet-remix-plugin/assets/131158645/3984404a-a400-40dc-b3d2-b9e9ad9ad5df)
My browser is Chrome version 116.0.5845.188

**Comment by Kuper8** [comment]
Windows 11, no plugins/adblocks

**Comment by cyborg112** [comment]
i am facing same issue except am running windows 10

**Comment by ferobugyi** [comment]
I have the same problem - Windows 11

**Comment by stranger80** [comment]
OK, we have been experiencing outages on the plugin backend, but this all now seems to have been rectified. Would you like to repeat your attempts and confirm if the compilation works as expected now?

**Comment by ferobugyi** [comment]
Everything is all right now. THX.
 
______________________________________________________________
> Od: "stranger80" ***@***.***>
> Komu: "NethermindEth/starknet-remix-plugin" ***@***.***>
> Dátum: 26.09.2023 20:45
> Predmet: Re: [NethermindEth/starknet-remix-plugin] Starknet cairo compile not working (Issue #127)
>
 
OK, we have been experiencing outages on the plugin backend, but this all now seems to have been rectified. Would you like to repeat your attempts and confirm if the compilation works as expected now?

**Comment by Kuper8** [comment]
> OK, we have been experiencing outages on the plugin backend, but this all now seems to have been rectified. Would you like to repeat your attempts and confirm if the compilation works as expected now?

After compilation this error: 
Error from IDE : [TIMEOUT] Timeout for call writeFile from Starknet try deleting the files: NethermindEth/StarknetByExample/listings/ch00-introduction/constructor/src/artifacts/lib.json and Nethermind...

And I don't know what to write in these fields: "names" and Smart contract"
![555](https://github.com/NethermindEth/starknet-remix-plugin/assets/131158645/d91e2a6a-1fac-4300-a282-255e5d5798b9)
