### ISSUE TITLE
Integrate plugin UI feedback from all sources

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#141]
Integrate all UI feedback and recommendations into an action plan to schedule

**Comment by prix0007** [comment]
### Plan of Action for UI Revamp
- Task A: Plugin UI Code Refactoring
  + Make folder structure for the UI seperate with each folder based on it's responsibility inside the `src` folder
      - `components` - store the UI elements
      - `contexts` - store the contexts in seperate files
      - `hooks` - store the UI Hooks being used all over the packages
      - `features` - each seperate feature present in the plugin
      - `utils` - utility or adhoc code should reside here for functions 
      - `atoms` - to store atomic data, stored via jotai
   + All the Styles for a component should reside in the same folder as the component itself, and should be imported in the component.
 
- Task B: Defining the Color system for plugin properly
   + We will define this on three standard level, and we will only use CSS Variables to store all the color based informations. The organization would be such as:
       - `palette.css` - this would be the file which will store all the colors only
           + for convience we will store 10 shades for each color suffixed to the color
           + we will store hex literals for colors as well as rgb information
       - `theme.css` - this file will contain the colors regarding the context for each usage
           + a good example would be like, text-light, text-dark, text-secondary
           + we will also consider few more colors groups `primary`, `secondary`, `error`, `warning`, `info`, `success` 
           + also adding sizes such as `font-sizes` and `spacing` would be added here also.
       - `component.css` - these css files would be individual files of css contained within each component to tweak styling based on scoped usage. 

- Task C: Implementing Changes from UI/UX Review
    + This will cover all the necessary changes required to make the UI/UX improved as per review feedback.
    + Figma Ref: https://www.figma.com/file/Fdao3PT4mJCBchTNAfmWma/Remix-Plugin?type=design&node-id=0-1&mode=design
        - C.a : Change Layouts as per design 
            + Modify the header to show the Plugin information for version and release status
            + Implement Environment Section for users to select between different environments
               - Also require adding customised radio button component
            + Move Plugin Information at the footer and clean the middle section to implement tabbed views.
        - C.b : Add tabbed styled different sections mentioned below:
            + Home
                - Modify Accordions as per new figma design + add elements on the accordian trigger based on state: "success" |  "compiling" | "failed" | "etc".
                - For each of feature within flow, make modification as per visible in figma.
            + Transactions
                - Modify cards to display the transactions as per figma design + add view to show number of transactions at the `Transaction` Tab view.
            + Info
                - Change Info section to be rendered from and markdown file, making it easier to edit and make changes frequently
