### ISSUE TITLE
Import multiple source files via URL

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#145]
Currently, we can specify URL arguments, but there is no support for importing multiple files/directory structures. I'm now exploring the plugin’s functions that can be called in the Remix URL. For example, the LearnEth plugin has a function called 'addRepository' that can be used like this: https://remix.ethereum.org/?#activate=LearnEth&call=LearnEth//addRepository//NethermindEth/StarknetByExample//main
Do you know of a way to import directories in the remix file manager? If not, would it be possible to add a custom function tailored to this need in our plugin, similar to what LearnEth has done?
The goal is to enhance the "open in Remix" feature of Starknet By Example, and it could also be used for an "open in Remix" button for verified contracts in Voyager.

**Comment by rjnrohit** [comment]
done
