### ISSUE TITLE
Release 0.2.4

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#160]
- [x] Notify Mktg about an estimated Release Date
- [x] Confirm README.md are consistent
- [ ] Confirm all code merged to main and Dev CI/CD deployment succeeded
- [x] Dev shakedown test
- [x] Create release version Tag
- [x] Create Release Notes
  - [ ] Share Release Notes with Mktg team
- [ ] Deploy to Prod 
- [ ] Prod shakedown test
- [ ] Release announcements
  - [ ] #shared-project-starknet-remix
  - [ ] Telegram group
  - [ ] Social Media (ask Marketing team)

**Comment by rjnrohit** [comment]
Done!
