### ISSUE TITLE
Feature: Resume plugin session

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#178]
### Feature Request Summary

I would like to be able to resume/continue a previous sesison with the plugin. I would like to see the history of my deployments/transactions, etc.

---

### Detailed Description

Evey time I restart the Remix, I lose track of contracts I have deployed, I need to compile & deploy again to bea ble to use Interact panel. I would lik ethe plugin to "remember" my contracts and allow to "connect" to them again to interact.
---

### UI Integration
TBC

---

### Backend Implementation
TBC
---

### Desired Behavior
TBC
---

### Examples from Other Projects
N/A

---

### Additional Information
N/A

---

**Comment by faytey** [comment]
Interesting, can i also hop on this

**Comment by rjnrohit** [comment]
Yeah sure @faytey

**Comment by kwkr** [comment]
Could I take this over @rjnrohit  @faytey ? I'm currently struggling to find a free issue in the ODHack and this one seems inactive.

**Comment by rjnrohit** [comment]
Yeah you can @kwkr , if @faytey is okay with this

**Comment by faytey** [comment]
@rjnrohit i'm okay with @kwkr taking it up, i started some little implementations though but insignificant, i'd focus on the other issue assigned me thanks

**Comment by kwkr** [comment]
Thank you! Can you assign it to me @rjnrohit?
