### ISSUE TITLE
Add a hint on u256 field 

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#183]
Users keep struggling with providing input values to `u256` fields in Remix plugin (Deploy and Invoke sections).
Add an '?' icon and when mouse hovers over it, display a 'tooltip' with an example input value.

**Comment by JorikSchellekens** [comment]
A better solution would be to integrate the form tool from prince https://www.npmjs.com/package/starknet-abi-forms

**Comment by rjnrohit** [comment]
Done! we are now in the middle of integrating starknet-abi-forms
