### ISSUE TITLE
Release 0.2.5

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#191]
- [ ] Notify Mktg about an estimated Release Date
- [ ] Confirm README.md are consistent
- [ ] Confirm all code merged to main and Dev CI/CD deployment succeeded
- [ ] Dev shakedown test
- [ ] Create release version Tag
- [ ] Create Release Notes
  - [ ] Share Release Notes with Mktg team
- [ ] Deploy to Prod 
- [ ] Prod shakedown test
- [ ] Release announcements
  - [ ] #shared-project-starknet-remix
  - [ ] Telegram group
  - [ ] Social Media (ask Marketing team)

**Comment by rjnrohit** [comment]
done!
