### ISSUE TITLE
Add syntax highlighting for Cairo

### ISSUE THREAD

**Issue by JorikSchellekens** [NethermindEth/starknet-remix-plugin#193]
Current syntax highlighting is close but not quite. There are a few strategies I can imagine for this:

- Write a syntax highlighter for Cairo in TextMate. This could be useful to other people in the ecosystem.
- Make a PR to remix to enable [tree-sitter](https://github.com/Menci/monaco-tree-sitter) and use a modified version of [AVNU's tree-sitter](https://github.com/avnu-labs/tree-sitter-cairo/tree/master) for Starknet. This would require compiling their C 'parser' (lexer, cough cough) to WASM.

**Comment by Cevedale** [comment]
Developing a TextMate syntax highlighter for Cairo is a key initiative aimed at enriching the broader coding ecosystem. Those undertaking this project are encouraged to become familiar with the intricacies of TextMate bundle creation, diligently define syntax rules, and conduct thorough testing to ensure an optimal coding experience for Cairo users in TextMate. The final step involves contributing the completed highlighter to the community, fostering collaboration and furthering Cairo's integration into TextMate.

Simultaneously, efforts are being made to enhance the parsing and code analysis capabilities of Remix for Starknet by integrating tree-sitter. To achieve this, individuals are advised to delve into the structure of Remix, assess the suitability of Tree-sitter for Starknet, and compile the C parser into WebAssembly (WASM). Rigorous testing is paramount to guarantee the accuracy and performance of the integration. The last step in this process entails contributing the implemented changes back to the Remix repository through a well-documented pull request, ensuring that the improvements are seamlessly incorporated into the Remix platform.

Throughout both endeavors, a set of considerations remains at the forefront. Prioritizing the creation of clear and comprehensive documentation is essential, aiding both users and contributors in understanding and utilizing the developed solutions. Active engagement with the relevant communities is emphasized, encouraging the gathering of feedback and fostering collaboration. Additionally, a forward-looking approach is advocated, ensuring that the solutions remain maintainable and adaptable to potential updates in Cairo, Starknet, TextMate, or Remix, thereby future-proofing the contributions.

**Comment by rjnrohit** [comment]
#209 dup
