### ISSUE TITLE
ERC20 Failed to compile

### ISSUE THREAD

**Issue by OverflowDev** [NethermindEth/starknet-remix-plugin#194]
![Uploading starknet.png…]()

I tried to deploy an ERC20 contract on Remix but I keep getting the error in the screenshot

I'm using this erc20 code
=> https://github.com/argentlabs/starknet-build/blob/main/cairo1.0/examples/erc20/ERC20.cairo 
and
=> https://cairo-by-example.com/examples/erc20/

I tried deploying this contract also but all is the same error 
=> https://book.starknet.io/ch01-00-getting-started.html

Note: I can compile and Deploy Counter.cairo

**Comment by OverflowDev** [comment]
Error while running process with id 68b10831-3195-4ba5-9c7e-757ad69471b2, error: Error: Error while running process with id 68b10831-3195-4ba5-9c7e-757ad69471b2, error: Error(FailedToReadFile(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
![starknet](https://github.com/NethermindEth/starknet-remix-plugin/assets/77024946/b67a10d2-cf9e-490e-8582-5697dd972586)

**Comment by rjnrohit** [comment]
It is fixed now!
