### ISSUE TITLE
Feature: Support external functions in `#[abi(embed_v0)]` and `#[abi(per_item)]` blocks

### ISSUE THREAD

**Issue by julio4** [NethermindEth/starknet-remix-plugin#195]
### Feature Request Summary

Currently the Interact tab only parse external functions from `#[external(v0)]` blocks but since cairo v2.3.0 it's recommended to use `#[abi(embed_v0)]` blocks (all external functions) and/or `#[abi(per_item)]` (with functions marked `#[external(v0)]` individually). It would be nice to support these external functions in the Interact tab.

**Comment by rjnrohit** [comment]
Sure, we will support these functions!. Thank you very much for highlighting this issue.
