### ISSUE TITLE
CI Pipeline (Check Scarb Version) : PR Creation/Push Failure

### ISSUE THREAD

**Issue by varex83** [NethermindEth/starknet-remix-plugin#270]
We have a problems with the new [workflow](https://github.com/NethermindEth/starknet-remix-plugin/blob/develop/.github/workflows/check-scarb-version.yml) that automatically runs every midnight (also can be manually dispatched). It works in the following way:

- It checks the latest release version of [Scarb](https://github.com/software-mansion/scarb)
- Compares with version, which plugin uses (it’s just stored at [.scarb-version](https://github.com/NethermindEth/starknet-remix-plugin/blob/develop/.scarb-version) file)
- If the version is outdated it:
	- Checks if there is already created PR, if not then goes forward
	- Creates a commit in the new branch update-scarb-v<VERSION>
	- Creates a PR with these changes on behalf of _action@github.com_ / GitHub Action

The problem is that from CI we can’t push changes because of missing `GITHUB_TOKEN` with the correct access level (now in the CI we use `GH_TOKEN_2` it was my try to use my own token).

---

From what I’ve tried:
- Creating PAT token with access to NethermindEth org, but scoped only to `starknet-remix-plugin` repository (hasn’t been approved yet), it’s stored in `GH_TOKEN` and `GH_TOKEN_3` secret
- Using my own token (classic version)

---

To test changes you need to:
- Set / Update the secret [here](https://github.com/NethermindEth/starknet-remix-plugin/settings/secrets/actions)
- Change the name in the workflow file [here](https://github.com/NethermindEth/starknet-remix-plugin/blob/8dd38461e32c38ec6da54bf23547231b36611acc/.github/workflows/check-scarb-version.yml#L75) and [here](https://github.com/NethermindEth/starknet-remix-plugin/blob/8dd38461e32c38ec6da54bf23547231b36611acc/.github/workflows/check-scarb-version.yml#L85)
- Manually dispatch the action [here](https://github.com/NethermindEth/starknet-remix-plugin/actions/workflows/check-scarb-version.yml)

---

[Link to the Slack conversation](https://demerzelsolutions.slack.com/archives/C02JYAUN0PL/p1725446017913529)

**Comment by ShantelPeters** [comment]
Hi @varex83 can i please work on this issue ?

**Comment by varex83** [comment]
Hey @ShantelPeters ! I've just fixed it right now :D 
But we have a lot of other interesting issues, so feel free to jump in!
