### ISSUE TITLE
Allow for different compilers

### ISSUE THREAD

**Issue by rjnrohit** [NethermindEth/starknet-remix-plugin#56]
Enable the dropdown and let the user select several versions of Cairo.
Because of the way this is done, most likely we'll need a folder for each version.

Proposed approach is to include the latest build of each major.minor version of Cairo compiler, starting from v2.0.0, so:
- https://github.com/starkware-libs/cairo/releases/tag/v2.0.2
- https://github.com/starkware-libs/cairo/releases/tag/v2.1.1
- https://github.com/starkware-libs/cairo/releases/tag/v2.2.0
- https://github.com/starkware-libs/cairo/releases/tag/v2.3.0

TBC with @JorikSchellekens 

Options:
- Have cairo binary versions included in API package (and run within single container).
- Have each Cairo verison compiler in a separate container image, and run compilers in containers

NOTE:
- The versioning must extend to Scarb as well (ie. choosing v2.2.0 applies to the full toolchain "Scarb+Cairo")
- For each Cairo version we need to have a dedicated devnet version -> this impacts the CI/CD and hosting approach (we will have more shared devnet versions)

**Comment by EdgarBarrantes** [comment]
If #64 is not going to be done, should this still be in to do?

**Comment by EdgarBarrantes** [comment]
The new deployment method could affect the implementation of this, I'd say this is blocked by #81

**Comment by rjnrohit** [comment]
# One possible approach: 

## For different versions of `Cairo`
1. for each version of `Cairo` create a separate pip environment on ecs and in each separate pip env run `starknet-devnet` instance on different ports. 
2. Selection of ports can be done using `version` state variables on the frontend side for the `starknet-devnet` api calls. 

Plausible code Snippet on the frontside: 

```js
let starknet_devnet_port = 5050
switch (cairo_version) {
     case v2.1.0: {
           port = 5051; 
     }
     case v1.9.0: {
           port = 5052; 
     }
     ...
    default : {
          port = 5050
    }
}

// Api call

const resp = await fetch(`${baseDevnetUrl}:${starknet_devnet_port}/method`) 
```

```bash
# command execution
$starknet-devnet --port 5051
```


## For different versions of `Scarb`
We can keep separate scarb binaries for each scarb version and execute the target scarb executable based on the selected `Scarb` version in the plugin

```bash
# for scarb version 0.7.0
$ scarb-0.7.0 build

# for scarb version 0.6.0
$ scarb-0.6.0 build
```

**Comment by EdgarBarrantes** [comment]
Hey @rjnrohit, jic, there's an internal doc for this [here](https://www.notion.so/nethermind/Different-compilers-1e1737eaa0d64792886ff2dd8178173e)

**Comment by stranger80** [comment]
- [ ] Create a solution concept, with components breakdown, diagram, etc.
- [ ] Define requirements for DevOps team and agree on the work split
- [ ] Design and implement React package changes to handle multiple versions

**Comment by EdgarBarrantes** [comment]
According to a call with amanusk there's no need to support Cairo 1 versions:
https://github.com/starkware-libs/cairo/releases/tag/v1.0.0
https://github.com/starkware-libs/cairo/releases/tag/v1.1.1

Which might simplify things.

Also, to research, there's a local configuration (per scarb folder) that can be used with asdf for multiple scarb versions, so eventually the mapping could be way simpler, and less containers deployed.

**Comment by stranger80** [comment]
Design concept diagram created for discussion with Angkor team: https://drive.google.com/file/d/1qUQAzFp3IU5_3Y2D3u7wdCqbIBHPmyWc/view (internal)
