### ISSUE TITLE
Prepare Remix plugin blogpost (including Scarb feature!)

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#67]
Prepare blogpost to announce the Starknet Remix plugin

**Comment by stranger80** [comment]
Blogpost draft prepared: https://www.notion.so/nethermind/Introductory-Blog-Post-41d2b4d3b1084d83b7c045f22c96e86e

**Comment by EdgarBarrantes** [comment]
This is currently waiting on #50 to be ready to include this on the post.

**Comment by EdgarBarrantes** [comment]
PR linked for style changes, otherwise this is done and was sent for marketing to review.
