### ISSUE TITLE
Publish Remix plugin announcement blogpost

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#68]
Steps needed to publish:
- Marketing review (Carla waiting for green light to review & comment)
- Add blogpost content to Medium
- Obtain approval and "press publish button" on Medium -> who needs to approve this blogpost?

Target for publish - once README.md/CONTRIBUTING.md and examples are consistent and Scarb feature is available online in Alpha

**Comment by stranger80** [comment]
Note: ping Anneli, then Jorik&|Swapnil

**Comment by EdgarBarrantes** [comment]
The article is "published" for proofreading on Medium.

**Comment by stranger80** [comment]
Need final nod from @JorikSchellekens before the publication. Aim for publication on 1.09.

**Comment by EdgarBarrantes** [comment]
All things done, will be published by Marketing on the 4.09
