### ISSUE TITLE
Implement Remix plugin versioning scheme

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#73]
- Agree the branching approach (eg. ensure master is the "official" branch, and "official builds" are built & tagged in master)
- Propose versioning scheme (probably semver-aligned)
  - eg. 0.1.x-alpha
- Include version label in plugin UI
- Implement version stamping in builds/deployments

**Comment by EdgarBarrantes** [comment]
Pretty much all done, except for the last part (version stamping on deployments), want to talk about that during the daily (related to the monorepo idea). For the moment there's a [minor release out there](https://github.com/NethermindEth/starknet-remix-plugin/releases/tag/v0.1.0), the label is looking like this:

![Image](https://github.com/NethermindEth/starknet-remix-plugin/assets/11295946/7877e48d-375a-451b-8b0f-9a2604488eaf)

Let me know if you see any improvements to be done.

**Comment by EdgarBarrantes** [comment]
I'll move the rest of the potential work on this to #89
