### ISSUE TITLE
Complete the CI/CD pipelines

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#81]
We would like to have online hosting for "prod" and "develop" instances of the Remix plugin. We need DNS entries and respective hosting for instances of the plugin UI app and API service (ECS hosted).
We would like to have automated CI/CD pipelines for build & deployment of remix plugin for both 'master' and 'develop' branches.

**Develop instance:** (hosted in "Nubia-nonprod" AWS account)

1. https://cairo-remix-dev.nethermind.io - plugin UI (React app) -> S3 static app
2. https://cairo-remix-api-dev.nethermind.io - plugin API (Rocket webserver) -> ECS hosted
3. https://starknet-remix-devnet.nethermind.io - devnet RPC instance (currently Python lib, want to move to Rust-based devnet) - how do we host this???
4. We would like to have GitHub Actions that build & upgrade points 1. and 2. above when PR is merged to `develop` branch.

**Prod instance:** (hosted in "nethermind" AWS account)

5. https://cairo-remix.nethermind.io - plugin UI (React app) -> S3 static app (http://starknet-remix-plugin-web.s3-website.us-east-2.amazonaws.com)
6. https://cairo-remix-api.nethermind.io - plugin API (Rocket webserver) -> ECS hosted
7. We would like to have GitHub Actions that build & upgrade points 1. and 2. above when PR is merged to `master` branch.

Once we have the above working, we would raise a PR to Remix project to repoint the Starknet plugin to the "prod" endpoint (point 5. above)

**Comment by EdgarBarrantes** [comment]
For point 6, maybe `https://cairo-remix-api.nethermind.io/` would be best, in case we ever change rocket for something else.

**Comment by stranger80** [comment]
Had a chat with @gehlotanish adn agreed the scope. @gehlotanish likely to get back to this task in w/c 4 Sep.

**Comment by gehlotanish** [comment]
@stranger80 I have merged the [PR](https://github.com/NethermindEth/starknet-remix-plugin/pull/103)

GH Action pipeline added.

**Comment by stranger80** [comment]
Had a chat with @gehlotanish to align on the behaviour of the Actions. Also reported that the Deploy step for the Plugin API service is failing.

**Comment by stranger80** [comment]
- S3/ECS deployment is now operating from develop branch for dev environments.
- The API service container is grinding to a halt after the first call to a functional API (eg. /cairo_version) - this is most likely due to the fact the first call to the compiler triggers "cargo run" which needs to build the cairo compiler first. This needs to be rectified:
  - Either build cairo during image build and try again 
  - or redesign the api service to not call "cargo run" but instead have a respective cairo compiler installed in image and called directly
