### ISSUE TITLE
Scarb project import

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/starknet-remix-plugin#94]
As a plugin user, I would like to have an ability to import a full scarb project from my local filesystem to Remix.

**Comment by rjnrohit** [comment]
There is no need to put efforts on this feature, file manager of remix IDE already provides the functionality
<img width="187" alt="Screenshot 2023-09-05 at 5 10 45 PM" src="https://github.com/NethermindEth/starknet-remix-plugin/assets/47271616/86037b2e-e9d4-415d-9eff-6cfc7929a3a1">
